### ISSUE TITLE
运行这个代码有一个bug，不知道是我环境的原因还是其他

### ISSUE THREAD

**Issue by sunyu2001** [rongliangtang/r-pan-server#1]
`class com.alibaba.fastjson.JSONObject cannot be cast to class com.tangrl.pan.server.modules.user.entity.RPanUser (com.alibaba.fastjson.JSONObject and com.tangrl.pan.server.modules.user.entity.RPanUser are in unnamed module of loader 'app')` 

在运行userCacheService，通过id获取RPanUser时，我想问问作者遇到这个错误了没，如果没有您的环境是什么样的配置？如果有，您是怎么解决的？  出现这个错误时，我的运行环境是jdk19，maven3.9.8；我尝试使用jdk8运行该项目，会出现错误
`Cannot find any provider supporting RSA/ECB/OAEPWithSHA-1AndMGF1Padding` 。如果有空的话，麻烦您答疑解惑，不胜感激。

**Comment by rongliangtang** [comment]
最好用jdk8运行，其他版本的jdk我没有试过

你这个错误应该是密码学库有问题，你可以粘贴完整的报错，问问gpt

**Comment by sunyu2001** [comment]
好的好的，非常感谢
